// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Block struct {
	ID            int64     `json:"id"`
	Height        int64     `json:"Height"`
	Proposer      string    `json:"proposer"`
	Moniker       string    `json:"moniker"`
	BlockHash     string    `json:"blockHash"`
	ParentHash    string    `json:"parentHash"`
	NumPrecommits int64     `json:"NumPrecommits"`
	NumTxs        int64     `json:"NumTxs"`
	TotalTxs      int64     `json:"TotalTxs"`
	Timestamp     time.Time `json:"timestamp"`
}

type PreCommit struct {
	ID               int64     `json:"id"`
	Height           int64     `json:"Height"`
	Round            int64     `json:"Round"`
	ValidatorAddress string    `json:"validatorAddress"`
	VotingPower      int64     `json:"VotingPower"`
	ProposerPriority int64     `json:"ProposerPriority"`
	Timestamp        time.Time `json:"timestamp"`
}

type Transaction struct {
	ID         int64     `json:"id"`
	Height     int64     `json:"Height"`
	TxHash     string    `json:"txHash"`
	Code       int64     `json:"Code"`
	Messages   string    `json:"messages"`
	Signatures string    `json:"signatures"`
	Memo       string    `json:"memo"`
	GasWanted  int64     `json:"GasWanted"`
	GasUsed    int64     `json:"GasUsed"`
	Timestamp  time.Time `json:"Timestamp"`
}

type Validator struct {
	ID                int64     `json:"id"`
	OperatorAddress   string    `json:"operatorAddress"`
	ConsensusAddress  string    `json:"consensusAddress"`
	ConsensusPubKey   string    `json:"consensusPubKey"`
	Moniker           string    `json:"moniker"`
	Identity          string    `json:"identity"`
	Website           string    `json:"website"`
	SecurityContact   string    `json:"securityContact"`
	Details           string    `json:"details"`
	Jailed            bool      `json:"Jailed"`
	Status            int64     `json:"Status"`
	Tokens            string    `json:"tokens"`
	DelegatorShares   string    `json:"delegatorShares"`
	UnbondingHeight   string    `json:"unbondingHeight"`
	UnbondingTime     string    `json:"unbondingTime"`
	Rate              string    `json:"rate"`
	MaxRate           string    `json:"maxRate"`
	MaxChangeRate     string    `json:"maxChangeRate"`
	UpdateTime        string    `json:"updateTime"`
	Timestamp         time.Time `json:"timestamp"`
	MinSelfDelegation string    `json:"minSelfDelegation"`
}
